name: build

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      # Install dependencies
      - run: npm ci

      # Lint
      - run: npm run lint -- --quiet

      # Build and output webpack stats to artifacts/webpack-stats.json
      - run: npm run build -- --json webpack-stats.json

      # Send webpack stats and build information to RelativeCI
      - name: Send webpack stats to RelativeCI
        uses: relative-ci/agent-action@v2
        with:
          webpackStatsFile: ./webpack-stats.json
          key: ${{ secrets.RELATIVE_CI_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            webpack-stats.json

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./dist
